### ISSUE TITLE
Wtf

### ISSUE THREAD

**Issue by Mushebeq** [WetCork/awesome-deezloader#2]
You're making it easy for Deezer if they want to take down applications you dumbass nigger, delete this

**Comment by WetCork** [comment]
Hey man relax!
Do you think Deezer doesn't already know these programs exist?
Also just do a simple internet search to end up in the [subbreddit](https://www.reddit.com/r/DeezloadersIsBack/) or just have a look at the famous list "[Awsesome Piracy](https://github.com/Igglybuff/awesome-piracy#music-downloading)".
Then as I said at the beginning of the readme, this list [already exist](https://gist.github.com/duttaditya18/f366c7694fe50d7c69f8654579112da5), I have only improved and expanded it.

**Comment by CHEF-KOCH** [comment]
He is a troll, he lists his own bots who are against Deezer and Telegram ToS public but complaints if others mention his (_or other Deezer related_) projects. If you do not want Deezer to find out about it, just do not list it in public.

Just close the ticket and move on.

**Comment by Drakonas** [comment]
Yeah well now deemix has been taken down too, so there is nothing left. Thanks.

**Comment by Drakonas** [comment]
While the OP's phrasing could have used some more respectful wording, the point made is correct. A list like this makes it super easy to get the websites taken down. Talk to any employee that works in the legal departments in any large company. They don't care to peruse reddit. It takes too much time. It's clear that they are watching your github, because every link you've posted, including your 3 links in that comment from March, have been taken down. I'd advise just shutting down this entire place, as it also goes against GitHub's policies.
